### ISSUE TITLE
Todo List - 第三次测试

### ISSUE THREAD

**Issue by jysperm** [HackPlan/RootPanel#75]
重要功能：
- [x] 测试资源限制
- [x] 测试部署 WordPress
- [x] 测试退订套餐
- [x] MongoDB 服务 & 权限测试
- [x] Memcached 自启动
- [x] Nginx: 向导模式
- [x] Nginx 目录权限检查
- [x] ps 中长用户名被省略
- [x] 检查数据库文件权限

可选功能：
- [ ] 测试 uwsgi
- [ ] 在服务支持页面上显示套餐列表
- [ ] 优化面板上的站点摘要
- [ ] 原生 Nginx 配置文件模式
- [x] SHOW DATABASES LIKE
- [ ] 在面板上显示磁盘占用率
- [ ] 流量统计和流量限制
- [ ] 实现机房列表和占用率
- [ ] 多语言
- [ ] #23 用 Node 重写原 RP 主机状态监视器
- [ ] 工单邮件
- [ ] 移动端 UI 适配
- [ ] pptp
- [ ] shadowsocks
- [ ] 工单类型
- [ ] 兑换码功能
- [ ] 用户资料设置
- [ ] 管理员面板更多功能
- [ ] 一键安装 WordPress
- [ ] 测试欠费自动删除

前端：
- [x] SSH KILL https://github.com/jysperm/RootPanel/commit/c0313ffd8b2e93465be00ab5132ca56959ad7a07
- [x] 给 JSON 编辑框换一个等宽字体
- [x] 服务开关现在不能工作
- [ ] 重构 yudong 的前端代码
- [ ] 将插件前端文件分散到插件目录
- [ ] 错误提示，不必要的情况下不刷新页面
