### ISSUE TITLE
Nginx command Todo List

### ISSUE THREAD

**Issue by jysperm** [HackPlan/RootPanel#76]
- [x] listen
- [x] server_name
- [x] root
- [x] location
- [x] try_files
- [x] fastcgi_pass
- [x] fastcgi_index
- [x] include
- [x] index
- [x] autoindex
- [x] proxy_pass
- [x] uwsgi_pass
- [x] proxy_set_header
- [x] proxy_redirect
- [ ] error_log
- [ ] access_log
- [ ] log_format
- [ ] auth_basic
- [ ] alias
- [ ] default_type
- [ ] error_page
- [ ] allow
- [ ] deny
- [ ] auth_basic_user_file
- [ ] proxy_hide_header
- [ ] ssl
- [ ] ssl_certificate
- [ ] ssl_certificate_key
- [ ] break
- [ ] if
- [ ] return
- [ ] rewrite
- [ ] set
- [ ] sub_filter
- [ ] sub_filter_once
- [ ] sub_filter_types
- [ ] charset
- [ ] rewrite_log
- [ ] fastcgi_param
- [ ] add_header
- [ ] expires
