### ISSUE TITLE
Todo List - 第四次测试

### ISSUE THREAD

**Issue by jysperm** [HackPlan/RootPanel#77]
功能：
- [ ] 用户组系统：允许在多个身份间切换
- [ ] 在资源充足时不执行资源限制
- [ ] 访问未绑定的域名是跳到 RP 主页
- [ ] 计算储存空间时计算数据库占用
- [ ] 每天强行结算
- [x] ! 磁盘限制
- [ ] 原生 Nginx 配置文件模式
- [x] ! 在面板上显示磁盘占用率
- [ ] 流量统计和流量限制
- [x] ! 实现机房列表
- [ ] 机房列表占用率
- [ ] 多语言
- [x] ! #23 用 Node 重写原 RP 主机状态监视器
- [ ] 工单邮件
- [ ] pptp
- [ ] shadowsocks
- [ ] 兑换码功能
- [ ] 用户资料设置
- [ ] ! 管理员面板：删除用户
- [ ] 一键安装 WordPress
- [x] ! 管理员工单页面
- [x] 网站列表：禁用站点
- [x] 网站列表

优化：
- [ ] 面板固定路径前缀，数据库前缀
- [ ] 支持绑定中文域名
- [ ] 更美观的时间展示
- [x] ! 在工单页面上显示工单状态
- [ ] 前端国际化
- [x] !  优化面板上的站点摘要
- [x] ! 在服务支持页面上显示套餐列表
- [ ] 移动端 UI 适配
- [x] ! 去除工单类型
- [x] 将插件前端文件分散到插件目录
- [x] 重构 yudong 除了 panel.coffee 之外的的前端代码
- [x] 优化错误提示
- [ ] ! 不必要的情况下不刷新页面
- [x] ! 注册时的用户名测试(/etc/passwd)

测试：
- [ ] 测试 uwsgi
- [ ] ! 测试欠费自动删除
