### ISSUE TITLE
Todo List - v0.5.0

### ISSUE THREAD

**Issue by jysperm** [HackPlan/RootPanel#78]
功能：
- [ ] !!! 用户组系统：允许在多个身份间切换
- [x] !!! 在资源充足时不执行资源限制
- [x] !!! 访问未绑定的域名跳到 RP 主页
- [x] !!! 计算储存空间时计算数据库占用
- [x] !!! 每天强行结算
- [ ] 原生 Nginx 配置文件模式
- [ ] 流量统计和流量限制
- [ ] 机房列表占用率
- [ ] 多语言
- [ ] ! 工单邮件
- [ ] pptp
- [ ] shadowsocks
- [ ] !!! 兑换码功能
- [ ] !!! 用户资料设置
- [ ] !!! 管理员面板：删除用户
- [ ] 一键安装 WordPress
- [ ] 数据同步脚本
- [ ] 自动测试
- [ ] 找回密码功能
- [ ] 数据迁移脚本

优化：
- [ ] ! 面板固定路径前缀，数据库前缀
- [x] !!! 支持绑定中文域名
- [ ] ! 更美观的时间展示
- [ ] 前端国际化
- [ ] 移动端 UI 适配
- [ ] ! 不必要的情况下不刷新页面

测试：
- [ ] 测试 uwsgi
- [x] !!! 测试欠费自动删除
