### ISSUE TITLE
Todo List - v0.8.0

### ISSUE THREAD

**Issue by jysperm** [HackPlan/RootPanel#83]
功能：
- [ ] !!! 数据同步脚本
- [ ] !!! 找回密码功能
- [x] 插件：supervisord
- [x] 多语言

优化：
- [ ] ! 面板固定路径前缀，数据库前缀
- [ ] 移动端 UI 适配
- [ ] ! 不必要的情况下不刷新页面
- [ ] 美化 WIKI 样式
- [ ] 美化邮件样式
- [ ] 整理 LESS
- [x] 国际化翻译
- [x] 美观的时间显示
- [x] get version in frontend
- [x] cache and localstorage
- [x] 管理员面板插件化

安全：
- [x] Nginx domain
- [x] CSRF

测试：
- [ ] MongoDB 新建数据库
- [ ] 磁盘统计信息的刷新机制
- [ ] 测试 uwsgi
- [X] 调试扣费
