### ISSUE TITLE
v0.9 Todo list

### ISSUE THREAD

**Issue by jysperm** [HackPlan/RootPanel#99]
- [x] 更换到 Mabolo, 将 router 中的逻辑移到 Model, 更换到 Promise
- [x] 新的插件和钩子机制 `app.extends.plugin.register`
- [x] 新的元件机制（#94），新的计费机制，新的通知机制
- [x] 使用 Backbone 重构前端
- [x] 为多节点做准备工作
- [ ] 完善管理员面板
- [ ] 重构单元测试
